const data1 = [
  {
    name: "Luyện thi #2",
    group_name: "AWS Basic",
    display_order: 34,
    lectures: [
      {
        title: "Kịch bản giảng dạy",
        display_order: 1,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
    ],
  },
  {
    name: "Lambda",
    group_name: "AWS Basic",
    display_order: 14,
    lectures: [
      {
        title: "Serverless Architecture",
        display_order: 1,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "What is AWS Lambda?",
        display_order: 2,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lambda Source events",
        display_order: 3,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lambda role & permission",
        display_order: 4,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Running your code on AWS Lambda",
        display_order: 5,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lambda use case",
        display_order: 6,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Integrate AWS lambda with S3",
        display_order: 7,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Integrate AWS Lambda with DynamoDB",
        display_order: 8,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lambda version and alias",
        display_order: 9,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lambda Alias",
        display_order: 10,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lambda Auto Scaling",
        display_order: 11,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Reserved concurrency",
        display_order: 12,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Throttling",
        display_order: 13,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
    ],
  },
  {
    name: "Auto Scaling Group (ASG) & Elastic Load Balancer (ELB)",
    group_name: "AWS Basic",
    display_order: 8,
    lectures: [
      {
        title: "Scaling Overview",
        display_order: 1,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title:
          "Lab: Tạo Auto Scaling Group cho web site đơn giản từ launch template",
        display_order: 2,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title:
          "Lab: Cập nhật web site bằng phương pháp thay đổi launch template",
        display_order: 3,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Triển khai web site kết hợp Auto Scaling và Load Balancer",
        display_order: 4,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: triển khai Load Balancer cho nhiều ứng dụng khác nhau",
        display_order: 5,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title:
          "Lab: Cấu hình SSL cho kết nối tới ứng dụng đứng sau Application Load Balancer",
        display_order: 6,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Launch Configuration & Launch Template",
        display_order: 7,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Tạo launch template và khởi tạo EC2 instance",
        display_order: 8,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Auto Scaling Group (ASG)",
        display_order: 9,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Sử dụng ASG + Launch template tạo cụm web app trên EC2",
        display_order: 10,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "ASG scaling policy & lifecycle hook",
        display_order: 11,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Elastic Load Balancer (ELB) introduction",
        display_order: 12,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Application Load Balancer (ALB)",
        display_order: 13,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Tích hợp ALB + ASG (part 1)",
        display_order: 14,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Tích hợp ALB + ASG (part 2)",
        display_order: 15,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Blue/Green deployment với ALB + ASG",
        display_order: 16,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Blue-Green deployment với ALB + ASG (part 2)",
        display_order: 17,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Network Load Balancer (NLB)",
        display_order: 18,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "ALB + ASG quiz",
        display_order: 19,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
    ],
  },
  {
    name: "Route 53",
    group_name: "AWS Basic",
    display_order: 4,
    lectures: [
      {
        title: "Module Overview",
        display_order: 1,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "DNS: Domain Name System",
        display_order: 2,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Transfer domain trên Google domain sang Route53",
        display_order: 3,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Public vs Private hosted zone",
        display_order: 5,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "CNAME vs R53 Alias",
        display_order: 6,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "R53 health check",
        display_order: 7,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Weighted Routing Policy",
        display_order: 8,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Failover Routing Policy",
        display_order: 9,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Weighted Routing Policy",
        display_order: 11,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
    ],
  },
  {
    name: "RDS - Aurora",
    group_name: "AWS Basic",
    display_order: 12,
    lectures: [
      {
        title: "Module Overview",
        display_order: 1,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: tạo và kết nối tới RDS MySQL",
        display_order: 2,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: RDS IAM Authentication",
        display_order: 3,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Tạo RDS MySQL, kết nối từ client",
        display_order: 4,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Import Sakila database vào RDS",
        display_order: 5,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Dựng WordPress trên EC2 kết nối RDS phần 1",
        display_order: 6,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Dựng WordPress trên EC2 kết nối RDS phần 2",
        display_order: 7,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title:
          "Lab: (Self study) thay đổi cấu hình Database và Monitor database workload, log, event",
        display_order: 8,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab; Encrypt running RDS",
        display_order: 9,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Quiz: RDS",
        display_order: 10,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
    ],
  },
  {
    name: "Storage",
    group_name: "AWS Basic",
    display_order: 7,
    lectures: [
      {
        title: "Căn bản EBS",
        display_order: 1,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Khác biệt giữa EBS và EFS vs S3",
        display_order: 2,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Tạo EBS, attach vào EC2, format và sử dụng",
        display_order: 3,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: sao chép dữ liệu từ EBS ở Region này sang Region khác",
        display_order: 4,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Chỉnh sửa data của EBS đang được attach vào EC2",
        display_order: 5,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Mã hoá ổ lưu trữ EBS",
        display_order: 6,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: EBS Multiple Attach",
        display_order: 7,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Khởi tạo EFS",
        display_order: 8,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Sử dụng EFS",
        display_order: 9,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Tạo Access Point trong EFS",
        display_order: 10,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Phân quyền thao tác EFS bằng File System Policy",
        display_order: 11,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Sử dụng EFS",
        display_order: 12,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "HW: Tạo EFS và mount Access Point vào nhiều EC2 instance",
        display_order: 13,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "HW: Tạo EC2 Launch Template để mount EFS",
        display_order: 14,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Replicate EFS từ Region A sang Region B",
        display_order: 15,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
    ],
  },
  {
    name: "Luyện thi #1",
    group_name: "AWS Basic",
    display_order: 33,
    lectures: [
      {
        title: "Kịch bản giảng dạy",
        display_order: 1,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
    ],
  },
  {
    name: "CloudFront",
    group_name: "AWS Basic",
    display_order: 6,
    lectures: [
      {
        title: "CloudFront Introduction",
        display_order: 1,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab 01: A video file distribution",
        display_order: 2,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab 02: A static website distribution",
        display_order: 3,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab 03: CloudFront Multiple Origins",
        display_order: 4,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab 04: CloudFront OAC for accessing S3 bucket",
        display_order: 5,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab 05: Private content with signed URLs",
        display_order: 6,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "CloudFront Quiz",
        display_order: 7,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Bonus",
        display_order: 8,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Distribution files by Cloudfront(Lab 1)",
        display_order: 9,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Host a static website with Cloudfront and S3 bucket(Lab 2)",
        display_order: 10,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Configuration Cloudfront OAC(Lab 4)",
        display_order: 11,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Private content with signed URL(Lab 5)",
        display_order: 12,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
    ],
  },
  {
    name: "EC2: Elastic Computing",
    group_name: "AWS Basic",
    display_order: 2,
    lectures: [
      {
        title: "\bCăn bản EC2",
        display_order: 1,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Tạo EC2 instance",
        display_order: 2,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Kết nối vào EC2",
        display_order: 3,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Mở cổng vào EC2 - Edit Inbound rule",
        display_order: 4,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Triển khai một static web site lên EC2",
        display_order: 5,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Cấp quyền để IAM user có thể quản lý EC2",
        display_order: 6,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: viết scripting khởi động EC2 sử  dụng  UserData",
        display_order: 7,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Viết script chạy mỗi khi EC2 reboot",
        display_order: 8,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Tạo AMI từ EC2 và tạo EC2 từ AMI",
        display_order: 9,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Home Work: Viết script khởi động trong EC2 User Data",
        display_order: 11,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
    ],
  },
  {
    name: "Điện toán đám mây - Amazon Web Service",
    group_name: "AWS Basic",
    display_order: 1,
    lectures: [
      {
        title: "Nhập môn AWS",
        display_order: 1,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Đăng nhập với tài khoản root vs tài khoản IAM",
        display_order: 2,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Sử dụng nhiều profile cho AWS CLI",
        display_order: 3,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Tạo cảnh báo chi phí vượt ngưỡng",
        display_order: 4,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Xem chi phí để biết dịch vụ nào tốn kém",
        display_order: 5,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Tối ưu chi phí sử dụng AWS",
        display_order: 6,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Quiz IAM",
        display_order: 7,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Quiz Intro to AWS",
        display_order: 8,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Quiz: Billing Cost",
        display_order: 9,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab 1_01: Đăng nhập với tài khoản root vs tài khoản IAM",
        display_order: 10,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab 1_02: Tạo cảnh báo chi phí vượt ngưỡng",
        display_order: 11,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
    ],
  },
  {
    name: "S3",
    group_name: "AWS Basic",
    display_order: 5,
    lectures: [
      {
        title: "S3 Introduction",
        display_order: 1,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab 01: Get Started with AWS CLI S3",
        display_order: 2,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab 02: S3 policy vs IAM policy",
        display_order: 3,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab 03: Hosting web site tĩnh lên S3",
        display_order: 4,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab 04: Từ EC2, upload file lên S3 dùng AWS CLI",
        display_order: 5,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab 05: Replication",
        display_order: 6,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab 06: Sharing objects by pre-signed URLs",
        display_order: 7,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab 07: S3 encryption",
        display_order: 8,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab 08: S3 CORS",
        display_order: 9,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "S3 Quiz",
        display_order: 10,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "HW: S3 Static website hosting",
        display_order: 11,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
    ],
  },
  {
    name: "Encryption & Security",
    group_name: "AWS Basic",
    display_order: 22,
    lectures: [
      {
        title: "Encryption + AWS Security Services",
        display_order: 1,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab-01-Encryption-on-Flight",
        display_order: 2,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab-02-Clientside-Encryption",
        display_order: 3,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab03-Serverside-Encryption",
        display_order: 4,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab-04-Parameter Stores and Secret Manager",
        display_order: 5,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
    ],
  },
  {
    name: "Networking - VPC",
    group_name: "AWS Basic",
    display_order: 3,
    lectures: [
      {
        title: "VPC Overview",
        display_order: 1,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lý thuyết mạng cơ bản",
        display_order: 2,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Exercise: quy hoạch subnet",
        display_order: 3,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "VPC & Subnet overview",
        display_order: 4,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Internet Gateway & Route Table",
        display_order: 5,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: (view) default VPC",
        display_order: 6,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Tạo VPC đơn giản với public subnet",
        display_order: 7,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Bastion hosts",
        display_order: 8,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Private Subnet & NAT",
        display_order: 9,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Tạo VPC với private subnet",
        display_order: 10,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: tạo bastion host",
        display_order: 11,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: VPC endpoint - S3 gateway endpoint",
        display_order: 12,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Quiz: VPC overview",
        display_order: 13,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "VPC Peering",
        display_order: 14,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Tạo kết nối giữa các VPC (VPC peering)",
        display_order: 15,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "VPN, Direct connect, Transit gateway",
        display_order: 16,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Kết nối các network với Transit Gateway",
        display_order: 17,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Quiz: VPC",
        display_order: 18,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
    ],
  },
  {
    name: "IAM",
    group_name: "AWS Basic",
    display_order: 1,
    lectures: [
      {
        title: "IAM Overview",
        display_order: 1,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Tạo IAM user, cấp quyền Administrator cho user này",
        display_order: 2,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: cho phép IAM user xem billing dashboard",
        display_order: 3,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: IAM Switch Role",
        display_order: 4,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Quiz: IAM",
        display_order: 5,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Quiz: IAM - self-resolving quizzes with explanation",
        display_order: 6,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: IAM User & Policy Getting Started (Console)",
        display_order: 7,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: IAM Access Key & Access Secret Key (Terminal, Powershell)",
        display_order: 8,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: IAM Role Getting Started",
        display_order: 9,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Practice: Access AWS From CLI (Terminal, Power shell)",
        display_order: 10,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
    ],
  },
  {
    name: "Elastic Cache",
    group_name: "AWS Basic",
    display_order: 10,
    lectures: [
      {
        title: "Tại sao ta lại cần cache",
        display_order: 1,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "ElastiCache là gì?",
        display_order: 2,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Hands On: Tạo một cache cluster",
        display_order: 3,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Sử dụng ElastiCache để tăng tốc WordPress",
        display_order: 4,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Cache deployment options",
        display_order: 5,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Memcached: cluster",
        display_order: 6,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Redis: Single-node cluster",
        display_order: 7,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Redis: cluster mode disabled",
        display_order: 8,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Redis: cluster mode enabled",
        display_order: 9,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Spring Boot + Elastic Cache",
        display_order: 10,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Secutiry",
        display_order: 11,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Tweaking cache performance",
        display_order: 12,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Quiz Elasticache",
        display_order: 13,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
    ],
  },
];

const data2 = [
  {
    name: "Cognitor: quản lý tài khoản người dùng",
    group_name: "AWS Advanced",
    display_order: 11,
    lectures: [
      {
        title: "API - REST API",
        display_order: 1,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "API Gateway overview",
        display_order: 2,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "AWS Cognito Overview",
        display_order: 3,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Cognito User Pool",
        display_order: 4,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Cognito Federated Identity",
        display_order: 5,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title:
          "Tạo temporary credential với Cognito Identity & Cognito User Pool",
        display_order: 6,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
    ],
  },
  {
    name: "Cloud Formation",
    group_name: "AWS Advanced",
    display_order: 9,
    lectures: [
      {
        title: "CloudFormation Introduction",
        display_order: 1,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab 01. Create a VPC and Subnet by CloudFormation",
        display_order: 2,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab 02. Create an EC2 by CloudFormation",
        display_order: 3,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab 03. Parameters in CloudFormation",
        display_order: 4,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab 04. Mappings and Conditions in CloudFormation",
        display_order: 5,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab 05. Cross-stack Reference",
        display_order: 6,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab 06. Nested Stacks",
        display_order: 7,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Bài tập Cloudformation",
        display_order: 8,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
    ],
  },
  {
    name: "Định hướng thi chứng chỉ SAP",
    group_name: "AWS Advanced",
    display_order: 32,
    lectures: [
      {
        title: "Slide : Ôn tập Full",
        display_order: 1,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
    ],
  },
  {
    name: "ECS, ECR, Fargate & Docker #2",
    group_name: "AWS Advanced",
    display_order: 20,
    lectures: [
      {
        title: "Docker and ecs overview",
        display_order: 1,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Tạo eks cluster bằng cli",
        display_order: 2,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
    ],
  },
  {
    name: "DynamoDB",
    group_name: "AWS Advanced",
    display_order: 23,
    lectures: [
      {
        title: "DynamoDB Introduction",
        display_order: 1,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab 01. CRUD by DynamoDB console",
        display_order: 2,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab 02. Access DynamoDB with CLI",
        display_order: 3,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: AWS CLI nạp dữ liệu JSON vào bảng",
        display_order: 4,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab 03. PartiQL",
        display_order: 5,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab 04. Access DynamoDB with boto3",
        display_order: 6,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab 05. DynamoDB Stream Trigger Lambda",
        display_order: 7,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "DynamoDB Quiz",
        display_order: 8,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
    ],
  },
  {
    name: "Monitoring & Audit: Cloud Watch, Cloud Trail, AWS Config",
    group_name: "AWS Advanced",
    display_order: 16,
    lectures: [
      {
        title: "Giới thiệu về AWS Monitoring & Audit",
        display_order: 1,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "CloudWatch Metrics + Dashboard",
        display_order: 2,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "CloudWatch Logs",
        display_order: 3,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "CloudWatch Agent",
        display_order: 4,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "CloudWatch Logs Metric Filters",
        display_order: 5,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "CloudWatch Alarms",
        display_order: 6,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Instance Recovery with CloudWatch Alarm",
        display_order: 7,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "CloudWatch Events",
        display_order: 8,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "EventBridge",
        display_order: 9,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "CloudTrail Overview",
        display_order: 10,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "CloudTrail Hands on",
        display_order: 11,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Hướng dẫn các bài lab và bài tập về nhà",
        display_order: 12,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
    ],
  },
  {
    name: "Terraform #1",
    group_name: "AWS Advanced",
    display_order: 17,
    lectures: [
      {
        title: "Slide and Lab",
        display_order: 1,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
    ],
  },
  {
    name: "Serverless Application Model (SAM)",
    group_name: "AWS Advanced",
    display_order: 21,
    lectures: [
      {
        title: "Lý thuyết",
        display_order: 1,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab 01: Install AWS SAM CLI",
        display_order: 2,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab 02: A simple API back-end by SAM",
        display_order: 3,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Cloud9 and SAM",
        display_order: 4,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab 03: S3 - SNS - Lambda app by SAM",
        display_order: 5,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab 05: Schedule Serverless App",
        display_order: 6,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "SAM - Hoàn thành phần 4 của bài lab thứ 2",
        display_order: 7,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
    ],
  },
  {
    name: "CICD CodePipeline, CodeBuild",
    group_name: "AWS Advanced",
    display_order: 24,
    lectures: [
      {
        title: "AWS CICD services",
        display_order: 1,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab 01: CodeCommit Hands-on",
        display_order: 2,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab 02: CodeBuild Hands-on",
        display_order: 3,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab 03: CodePipeline Hands-on",
        display_order: 4,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab 04: CodeDeploy Hands-on",
        display_order: 5,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "CICD in AWS - QUiz",
        display_order: 6,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
    ],
  },
  {
    name: "Integration and Messaging: SQS, SNS & Kinesis",
    group_name: "AWS Advanced",
    display_order: 31,
    lectures: [
      {
        title: "Module Overview",
        display_order: 1,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Cấu hình S3 send event SQS queue",
        display_order: 2,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Text To Audio Using AWS Polly - part 1",
        display_order: 3,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Pub Sub",
        display_order: 4,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Quiz: Decoupling Architecture",
        display_order: 5,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
    ],
  },
  {
    name: "AWS SDK",
    group_name: "AWS Advanced",
    display_order: 15,
    lectures: [
      {
        title: "Slide",
        display_order: 1,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: SDK credentials",
        display_order: 2,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: AWS SDK doc examples",
        display_order: 3,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Change RDS Aurora instance class",
        display_order: 4,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Answer: Change RDS Aurora instance class",
        display_order: 5,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Lab: Migrate Aurora cluster to global",
        display_order: 6,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Answer: Migrate Aurora cluster to global",
        display_order: 7,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
    ],
  },
  {
    name: "Thực hành các dạng kiến trúc AWS thường gặp",
    group_name: "AWS Advanced",
    display_order: 13,
    lectures: [
      {
        title: "Thực hành các dạng kiến trúc AWS thường gặp",
        display_order: 1,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
    ],
  },
  {
    name: "AWS Batch + AWS Beanstalk",
    group_name: "AWS Advanced",
    display_order: 25,
    lectures: [
      {
        title: "AWS Batch",
        display_order: 1,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "AWS Batch Concept",
        display_order: 2,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "AWS Batch (lab)",
        display_order: 3,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "AWS Batch Best practice",
        display_order: 4,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "AWS Beanstalk",
        display_order: 5,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "AWS Beanstalk concept",
        display_order: 6,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Beanstalk (lab)",
        display_order: 7,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
    ],
  },
  {
    name: "ECS, ECR, Fargate & Docker #1",
    group_name: "AWS Advanced",
    display_order: 19,
    lectures: [
      {
        title: "Docker overview",
        display_order: 1,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "ECR Overview",
        display_order: 2,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "ECS concepts",
        display_order: 3,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "ECS Hands on",
        display_order: 4,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Fargate",
        display_order: 5,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "EKS Overview",
        display_order: 6,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "EKS Part II",
        display_order: 7,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
    ],
  },
  {
    name: "Terraform #2",
    group_name: "AWS Advanced",
    display_order: 18,
    lectures: [
      {
        title: "Slide updated",
        display_order: 1,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
    ],
  },
  {
    name: "QUIZ - 715",
    group_name: "Bộ đề Test",
    display_order: 30,
    lectures: [
      {
        title: "Whizlab AWS Practice 1",
        display_order: 1,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Whizlab AWS Practice 2",
        display_order: 2,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Whizlab AWS Practice 3",
        display_order: 3,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Whizlab AWS Practice 4",
        display_order: 4,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Whizlab AWS Practice 5",
        display_order: 5,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Udemy AWS Practice 1",
        display_order: 6,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Udemy AWS Practice 2",
        display_order: 7,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Udemy AWS Practice 3",
        display_order: 8,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Udemy AWS Practice 4",
        display_order: 9,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Udemy AWS Practice 5",
        display_order: 10,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Udemy AWS Practice 6",
        display_order: 11,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
    ],
  },
  {
    name: "QUIZ AWS DVA",
    group_name: "Bộ đề Test",
    display_order: 29,
    lectures: [
      {
        title: "Test 1",
        display_order: 1,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Test 2",
        display_order: 2,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Test 3",
        display_order: 3,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Test 4",
        display_order: 4,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Test 5",
        display_order: 5,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Test 6",
        display_order: 6,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Test 7",
        display_order: 7,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Test 8",
        display_order: 8,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Test 9",
        display_order: 9,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Test 10",
        display_order: 10,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Test 11",
        display_order: 11,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "Test 12",
        display_order: 12,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
    ],
  },
  {
    name: "QUIZ AWS SAA C03",
    group_name: "Bộ đề Test",
    display_order: 28,
    lectures: [
      {
        title: "QUIZ AWS SA 03 - Test 1",
        display_order: 1,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "QUIZ AWS SA 03 - Test 2",
        display_order: 2,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "QUIZ AWS SA 03 - Test 3",
        display_order: 3,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "QUIZ AWS SA 03 - Test 4",
        display_order: 4,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "QUIZ AWS SA 03 - Test 5",
        display_order: 5,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "QUIZ AWS SA 03 - Test 6",
        display_order: 6,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
    ],
  },
  {
    name: "QUIZ AWS SAP",
    group_name: "Bộ đề Test",
    display_order: 27,
    lectures: [
      {
        title: "Diagnostic",
        display_order: 1,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "PRO 01",
        display_order: 2,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "PRO 02",
        display_order: 3,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "PRO 03",
        display_order: 4,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
      {
        title: "PRO 04",
        display_order: 5,
        video_id: "",
        video_duration: 0,
        server_id: 0,
      },
    ],
  },
];
